### ISSUE TITLE
Local setup fails because of `db_entities` not found

### ISSUE THREAD

**Issue by ArnavBalyan** [OcularEngineering/ocular#41] opened 2024-04-16 05:39 UTC
ocular-db-migration  | Resolution path: db_entities
ocular-db-migration  |     at Object.resolve (/usr/src/app/node_modules/awilix/lib/container.js:252:23)
ocular-db-migration  |     at /usr/src/app/packages/ocular/dist/ocular/src/loaders/database.js:50:38
ocular-db-migration  |     at step (/usr/src/app/packages/ocular/dist/ocular/src/loaders/database.js:33:23)
ocular-db-migration  |     at Object.next (/usr/src/app/packages/ocular/dist/ocular/src/loaders/database.js:14:53)
ocular-db-migration  |     at /usr/src/app/packages/ocular/dist/ocular/src/loaders/database.js:8:71
ocular-db-migration  |     at new Promise (<anonymous>)
ocular-db-migration  |     at __awaiter (/usr/src/app/packages/ocular/dist/ocular/src/loaders/database.js:4:12)
ocular-db-migration  |     at /usr/src/app/packages/ocular/dist/ocular/src/loaders/database.js:43:43
ocular-db-migration  |     at /usr/src/app/packages/ocular/dist/ocular/src/data-source.js:77:61
ocular-db-migration  |     at step (/usr/src/app/packages/ocular/dist/ocular/src/data-source.js:33:23)
ocular-db-migration  | npm ERR! Lifecycle script `typeorm` failed with error:
ocular-db-migration  | npm ERR! Error: command failed
ocular-db-migration  | npm ERR!   in workspace: @ocular/ocular@1.0.0
ocular-db-migration  | npm ERR!   at location: /usr/src/app/packages/ocular
ocular-db-migration exited with code 1

**Comment by Vivek-Lahole** [comment] 2024-04-17 05:10
This issue was resolved by commit **9a6d7d1e788891ba035d520ef227204f71c5e29b** . The commit adjusted the **Resolution path: db_entities**  that were causing the error. You can view the changes in detail [here](https://github.com/OcularEngineering/ocular/commit/9a6d7d1e788891ba035d520ef227204f71c5e29b). Please update your local branch and verify that the issue is resolved on your end too.

**Comment by ArnavBalyan** [comment] 2024-04-17 09:34
Hey @Vivek-Lahole it seems running `docker compose -f docker-compose.dev.yml up` gives the same error. I am using the latest main.

**Comment by louismurerwa** [comment] 2024-04-17 16:23
We have to rollback that change unfortunately because it was not compatible with the MacOS operating system. 

The main issue is the Windows use backslashes for the file system and MacOS use forward slashes. So when trying to read files on the local machine the app breaks.

**Comment by louismurerwa** [comment] 2024-05-08 20:10
@ArnavBalyan This has been fixed in https://github.com/OcularEngineering/ocular/pull/72

**Closed** 2024-05-08 20:10 UTC
